### ISSUE TITLE
Update default chain to Harmony

### ISSUE THREAD

**Issue by anhtl2505** [OpenWorldVision/OW_PM#15]
Update default chain from BSC to Harmony
Adding Harmony testnet environment

**Comment by nnphuong9718** [comment]
Link test đây nha anh https://c3d6dbcf.open-world.pages.dev/entry

**Comment by nnphuong9718** [comment]
Link test: https://c3d6dbcf.open-world.pages.dev/entry

**Comment by anhtl2505** [comment]
Perform testing and verify the default chain:

- [x] When connect to our web, will show the request for switching the chain from other to Harmony.

- [x] The default chain is Harmony.

- [x] When connect to Harmony will display correct data base on wallet's information

**Comment by nnphuong9718** [comment]
new test link: https://a7597506.open-world.pages.dev/entry

**Comment by nntam2013** [comment]
Done
