### ISSUE TITLE
Openian/Selling

### ISSUE THREAD

**Issue by anhtl2505** [OpenWorldVision/OW_PM#30]
- [ ] Update background for Selling page
- [ ] Add model Sell item
- [ ] Add logic and validation for price, amount for selling item.
- [ ] Add model result after click sell item.

**Comment by VinhTruong2001** [comment]
I finished 3 first tasks, but there's still some minor bugs in UI so I need some time to fix that.

- [x]  Update background for Selling page
- [x]  Add model Sell item
- [x]  Add logic and validation for price, amount for selling item.
