### ISSUE TITLE
Castle UI

### ISSUE THREAD

**Issue by anhtl2505** [OpenWorldVision/OW_PM#33]
- [ ]  Main Map Castle
- [ ]  Add Flow/modal Shop
- [ ]  Apply buying NFT card

**Comment by VinhTruong2001** [comment]
I finish the UI and flow for Shop modal in Castle, also the feature buying NFT card. Can you checking it ? @anhtl2505 

- [x]  Main Map Castle
- [x]  Add Flow/modal Shop
- [x] Apply buying NFT card

**Comment by anhtl2505** [comment]
Finish checking, I will close this task
