### ISSUE TITLE
Food Court UI

### ISSUE THREAD

**Issue by anhtl2505** [OpenWorldVision/OW_PM#38]
- [x] Update UI for Foodcourt 
- [x] Add modal buyer board. 
- [x] Update logic buy, 
- [x] Add Pagination for listing item. 
- [x] Responsive for mobile view

**Comment by QuangHiep2000** [comment]
This task has been completed and can test.

**Comment by anhtl2505** [comment]
Finish testing. We're still having some issues on Harmony testnet but not our scope so I will close the ticket.
