### ISSUE TITLE
Apply and optimize new loading page and icon

### ISSUE THREAD

**Issue by anhtl2505** [OpenWorldVision/OW_PM#42]
- [x]  Improve loading speed for Castle
- [x]  Improve loading speed Worldmap
- [x]  Adding opacity for loading background
- [x]  Optimize and decrease time for loading page.

**Comment by nntam2013** [comment]
This issue has been resolved in the dev branch. You can test and give me some feedback.

**Comment by anhtl2505** [comment]
We're adding more validations popup and optimizing the loading time. For now, it's ok, I will double-check when we finish all validation popups. 
Complete and will confirm in other tickets.
