### ISSUE TITLE
Create https://onebond.openworld.vision to sell Open Bond on harmony

### ISSUE THREAD

**Issue by openworldnow** [OpenWorldVision/OW_PM#44]
To create LP Pool

**Comment by cschanhniem** [comment]
- buy bond uses ONE (not WONE)
- 50% is used to convert into USDC and add to OPEN/USDC pool , 50% is to OPEN/ONE
- price is fixed not using oracle
- each contract is only available to be bought after a TimeStamp, which is showed on UI
- make sure error handling carefully to avoid mistake/complain from users
- carefully review security bugs
- max buy is 5000 OPEN per time per wallet, only can buy 1 time per 1 minute per wallet

**Comment by nntam2013** [comment]
The team is developing this feature, and we'll release the testnet next week.

**Comment by cschanhniem** [comment]
Another note, pls set domain for this app at http://onebond.openworld.vision/
